name: Git Clone, Unzip, Install, and Run

on:
  push:
    branches:
      - main  # Jalankan setiap ada push di branch 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repository utama
    - name: Checkout repository utama
      uses: actions/checkout@v3

    # Step 2: Clone animeZoneGit repository dengan autentikasi
    - name: Clone animeZoneGit repository
      run: |
        git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/Anime-ZoneGit/animeZoneGit.git

    # Step 3: Pindah ke direktori animeZoneGit
    - name: Change directory to animeZoneGit
      run: cd animeZoneGit

    # Step 4: Install unzip jika belum ada, lalu unzip file
    - name: Unzip B-SML2.zip
      run: |
        sudo apt-get update && sudo apt-get install -y unzip  # Install unzip
        unzip animeZoneGit/B-SML2.zip -d ./animeZoneGit  # Unzip B-SML2.zip

    # Step 5: Install npm dependencies
    - name: Install npm dependencies
      run: |
        cd animeZoneGit
        npm install

    # Step 6: Start the npm application
    - name: Start the application
      run: |
        cd animeZoneGit
        npm start
